name: space_launches
description: Space missions launches calendar
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^1.0.0
  retrofit: ^3.0.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  auto_route: ^3.1.3
  launch_details:
    path: ../features/launch_details/
  upcoming_launches:
    path: ../features/upcoming_launches/

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.1.5  
  freezed: ^1.0.0
  json_serializable: ^6.0.1
  retrofit_generator: ^3.0.0+2
  injectable_generator: ^1.5.2
  auto_route_generator: ^3.1.0

flutter:
  uses-material-design: true
