output-localization-file: upcoming_launches_localizations.dart
output-class: UpcomingLaunchesLocalizations
preferred-supported-locales: [en, fa]
synthetic-package: false
output-dir: ./lib/l10n/generated